services:
  stargate-network:
    image: devidian/rw-stargate-network:0.1.0
    restart: unless-stopped
    environment:
      PORT: 47016
      MONGODB_URI: mongodb://stargate-mongo:27017
      MONGODB_DATABASE: rw_stargate_network
    ports:
      - "127.0.0.1:47016:47016"
    depends_on:
      - stargate-mongo
  stargate-mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - stargate-mongo-data:/data/db
volumes:
  stargate-mongo-data: {}
